import{useEffect,useState}from'react';import{useDispatch,useSelector}from'react-redux';import{fetchJobs,fetchStats,applyJob}from'./redux/jobsSlice';

const API=import.meta.env.VITE_API_URL||'http://localhost:8080/api';

function Login({onLogin}){const[role,setRole]=useState('APPLICANT');const[email,setEmail]=useState('applicant@hireflow.com');const[password,setPassword]=useState('applicant123');const[error,setError]=useState('');const submit=async e=>{e.preventDefault();setError('');try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,role})});const d=await r.json();if(!r.ok)throw Error(d.message||'Login failed');localStorage.setItem('hireflowUser',JSON.stringify(d.user));localStorage.setItem('hireflowToken',d.token);onLogin(d.user)}catch(e){setError(e.message)}};const choose=r=>{setRole(r);if(r==='APPLICANT'){setEmail('applicant@hireflow.com');setPassword('applicant123')}else{setEmail('recruiter@hireflow.com');setPassword('recruiter123')}};return <div className="auth-page"><div className="auth-card"><div className="auth-brand">Hire<span>Flow</span></div><p className="auth-sub">Select your workspace</p><div className="role-tabs"><button type="button" className={role==='APPLICANT'?'active':''} onClick={()=>choose('APPLICANT')}>Applicant</button><button type="button" className={role==='RECRUITER'?'active':''} onClick={()=>choose('RECRUITER')}>Recruiter</button></div><h1>{role==='APPLICANT'?'Find your next opportunity':'Manage your hiring pipeline'}</h1><p className="auth-copy">{role==='APPLICANT'?'Search jobs and apply to roles.':'Manage jobs, applicants and recruitment.'}</p><form onSubmit={submit}><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/>{error&&<div className="error">{error}</div>}<button className="auth-submit">{role==='APPLICANT'?'Sign in as Applicant':'Sign in as Recruiter'}</button></form><small>Demo credentials are pre-filled.</small></div></div>}

function Header({user,onLogout}){return <header><div><span className="logo">Hire<span>Flow</span></span><p>{user.role==='RECRUITER'?'Recruiter Workspace':'Applicant Workspace'}</p></div><div className="user-actions"><span>{user.name}</span><button onClick={onLogout}>Logout</button></div></header>}

function Applicant({user,onLogout}){const d=useDispatch(),{page,status,applyStatus,appliedJob,error}=useSelector(s=>s.jobs);const[q,setQ]=useState('');useEffect(()=>{d(fetchJobs({q,page:0,size:8,sortBy:'id',direction:'desc'}))},[d,q]);return <><Header user={user} onLogout={onLogout}/><main><section className="dashboard-hero"><span className="eyebrow">APPLICANT DASHBOARD</span><h1>Welcome, {user.name}</h1><p>Search opportunities and apply to your next role.</p></section><section className="search-card"><form onSubmit={e=>e.preventDefault()}><div className="search-input"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search jobs, companies or skills..."/></div><button>Search</button></form></section><div className="content-head"><div><span className="eyebrow">OPEN POSITIONS</span><h2>Available jobs</h2></div></div>{error&&<div className="error">{error}</div>}{status==='loading'?<div className="loading">Loading jobs...</div>:<section className="jobs">{(page?.content||[]).map(job=><article className="job" key={job.id}><div className="company-icon">{job.company[0]}</div><div><h3>{job.title}</h3><p className="company">{job.company} · {job.location}</p><p className="description">{job.description}</p><div className="tags">{job.skills.split(',').map(s=><span key={s}>{s.trim()}</span>)}</div></div><div className="job-side"><strong>{job.salary||'Salary not disclosed'}</strong><button onClick={()=>d(applyJob(job.id))} disabled={applyStatus==='loading'}>{appliedJob?.jobId===job.id?'Applied':'Apply now'}</button></div></article>)}</section>}</main></>}

function Recruiter({user,onLogout}){const d=useDispatch(),{stats}=useSelector(s=>s.jobs);useEffect(()=>{d(fetchStats())},[d]);return <><Header user={user} onLogout={onLogout}/><main><section className="dashboard-hero"><span className="eyebrow">RECRUITER DASHBOARD</span><h1>Welcome, {user.name}</h1><p>Manage your hiring pipeline from one workspace.</p></section><section className="stats">{[['Total Jobs',stats?.totalJobs??'—'],['Full Time',stats?.fullTimeJobs??'—'],['Internships',stats?.internshipJobs??'—'],['Remote',stats?.remoteJobs??'—']].map(x=><div className="stat" key={x[0]}><b>{x[1]}</b><span>{x[0]}</span></div>)}</section><section className="dashboard-grid">{['Post a Job','Manage Jobs','Applicants','Analytics','Interviews','Notifications'].map(x=><article className="dash-card" key={x}><h3>{x}</h3><p>Recruiter workspace module</p><button>Open</button></article>)}</section></main></>}

export default function App(){const[user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('hireflowUser'))}catch{return null}});const logout=()=>{localStorage.removeItem('hireflowUser');localStorage.removeItem('hireflowToken');setUser(null)};if(!user)return <Login onLogin={setUser}/>;return user.role==='RECRUITER'?<Recruiter user={user} onLogout={logout}/>:<Applicant user={user} onLogout={logout}/>}
